# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00f96f0aa1330df7c6ae2374d02decd1403866fe8c3a039c822712b01e27d11dc19c1785be61c382f1664d15de463489da84884615f8c87154fa0704e80e35e9

test:
  secret_key_base: 46dd39b95d0dd9aa147f84738bdf10fd78686f4c3a3a1d7d52713081f5e546d74ae65cc345d8694607c8740b32f1e81b666d6353f17f3d7b268590d888592c6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
